#!/bin/sh
# harness write — File writer with marker management
# Reads generated content → writes to CLAUDE.md and project files
# NEVER overwrites user content outside HARNESS:START/END markers

MARKER_START_V2='<!-- HARNESS:START v2'
MARKER_END_V2='<!-- HARNESS:END v2 -->'

# ── Write CLAUDE.md ──────────────────────────────────────────────────────────

write_claude_md() {
    log_step "Writing CLAUDE.md..."

    _map_file="${HARNESS_DIR}/.map-content.md"

    if [ ! -f "$_map_file" ]; then
        log_error "No map content found. Run generate first."
        return 1
    fi

    _map_content=$(cat "$_map_file")

    if [ "$FLAG_DRY_RUN" = true ]; then
        log_step "[dry-run] Would write CLAUDE.md with harness map"
        if has_v2_markers "$CLAUDE_MD"; then
            log_step "[dry-run] Existing markers found — would replace marker content only"
        elif has_v1_markers "$CLAUDE_MD"; then
            log_step "[dry-run] Legacy v1 markers found — would migrate to v2"
        elif [ -f "$CLAUDE_MD" ]; then
            log_step "[dry-run] Existing CLAUDE.md without markers — would prepend harness block"
        else
            log_step "[dry-run] No CLAUDE.md — would create new file"
        fi
        return 0
    fi

    # Migrate v1 markers if present
    if has_v1_markers "$CLAUDE_MD"; then
        log_step "Migrating v1 markers to v2..."
        # Replace v1 markers with v2
        sed -i.bak \
            -e "s|<!-- HARNESS:START --|${MARKER_START_V2} — Auto-generated by harness-toolkit v${TOOLKIT_VERSION}. Do not edit. -->|" \
            -e "s|<!-- HARNESS:END -->|${MARKER_END_V2}|" \
            "$CLAUDE_MD"
        rm -f "${CLAUDE_MD}.bak"
    fi

    # Write using marker replacement
    _new_content_file=$(mktemp)
    printf '%s\n' "$_map_content" > "$_new_content_file"
    replace_marker_content "$CLAUDE_MD" "$_new_content_file"
    rm -f "$_new_content_file"

    log_verbose "CLAUDE.md updated"
}

# ── Write Scoped CLAUDE.md ───────────────────────────────────────────────────

write_scoped_configs() {
    _tier=$(json_get "$CONFIG_FILE" '.tier')

    # Only for standard+ tiers
    if ! tier_at_least "$_tier" "standard"; then
        log_verbose "Skipping scoped configs (tier: $_tier)"
        return 0
    fi

    log_step "Writing scoped configs..."

    _shape_type=$(json_get "$CONTEXT_FILE" '.shape.type')

    # For monorepos, create scoped CLAUDE.md in each app/service directory
    if [ "$_shape_type" = "monorepo" ]; then
        _services=$(json_get "$CONTEXT_FILE" '.shape.services[]' 2>/dev/null)
        for _svc in $_services; do
            _svc_dir="$PROJECT_ROOT/apps/$_svc"
            [ ! -d "$_svc_dir" ] && continue

            _scoped_claude="$_svc_dir/CLAUDE.md"

            if [ "$FLAG_DRY_RUN" = true ]; then
                log_step "[dry-run] Would write scoped config: $_scoped_claude"
                continue
            fi

            _scoped_content="# ${_svc} — Scoped Rules

This module is part of the monorepo. See root CLAUDE.md for global rules.

## Module-specific rules
- Follow the conventions in the root harness rules
- This module's specific patterns and concerns go here

> Edit below the HARNESS:END marker to add custom rules for this module."

            _scoped_file=$(mktemp)
            printf '%s\n' "$_scoped_content" > "$_scoped_file"

            if [ ! -f "$_scoped_claude" ]; then
                # Create new scoped file
                replace_marker_content "$_scoped_claude" "$_scoped_file"
                log_verbose "Created scoped config: $_scoped_claude"
            elif ! has_v2_markers "$_scoped_claude"; then
                # Existing file without markers — prepend
                replace_marker_content "$_scoped_claude" "$_scoped_file"
                log_verbose "Added harness markers to: $_scoped_claude"
            else
                # Has markers — update
                replace_marker_content "$_scoped_claude" "$_scoped_file"
                log_verbose "Updated scoped config: $_scoped_claude"
            fi

            rm -f "$_scoped_file"
        done
    fi

    # For any project: detect large top-level source directories
    for _dir in "$PROJECT_ROOT/src/"*/; do
        [ ! -d "$_dir" ] && continue
        _name=$(basename "$_dir")
        _scoped_claude="$_dir/CLAUDE.md"

        # Only create if directory has significant content (>10 files)
        _file_count=$(find "$_dir" -maxdepth 2 -type f 2>/dev/null | wc -l | tr -d ' ')
        if [ "$_file_count" -lt 10 ]; then
            continue
        fi

        if [ "$FLAG_DRY_RUN" = true ]; then
            log_step "[dry-run] Would create scoped config for src/$_name/ ($_file_count files)"
            continue
        fi

        if [ ! -f "$_scoped_claude" ]; then
            _scoped_content="# ${_name} module

> Auto-generated by harness-toolkit. Add module-specific rules below HARNESS:END marker.

## Context
This module contains $_file_count files. Refer to root CLAUDE.md for global rules."

            _scoped_file=$(mktemp)
            printf '%s\n' "$_scoped_content" > "$_scoped_file"
            replace_marker_content "$_scoped_claude" "$_scoped_file"
            rm -f "$_scoped_file"
            log_verbose "Created scoped config: src/$_name/CLAUDE.md"
        fi
    done
}

# ── Write Hooks Config ───────────────────────────────────────────────────────

write_hooks_config() {
    log_step "Configuring hooks in settings.json..."

    _settings_dir="$PROJECT_ROOT/.claude"
    _settings_file="$_settings_dir/settings.json"

    if [ "$FLAG_DRY_RUN" = true ]; then
        log_step "[dry-run] Would update .claude/settings.json with hook entries"
        return 0
    fi

    ensure_dir "$_settings_dir"

    # Create settings.json if not exists
    if [ ! -f "$_settings_file" ]; then
        echo '{}' > "$_settings_file"
    fi

    # Build hooks config
    _hooks_json=$(cat <<'HOOKSEOF'
{
    "hooks": {
        "PreToolUse": [
            {
                "matcher": "Bash",
                "hook": [".claude/harness/hooks/pre-command.sh"],
                "description": "[harness] Command risk classification"
            }
        ]
    }
}
HOOKSEOF
)

    # Check if formatter hook exists
    if [ -f "$HOOKS_DIR/post-edit.sh" ]; then
        _hooks_json=$(printf '%s' "$_hooks_json" | jq '.hooks.PostToolUse = [
            {
                "matcher": "Edit",
                "hook": [".claude/harness/hooks/post-edit.sh"],
                "description": "[harness] Auto-format after edit"
            }
        ]')
    fi

    # Merge with existing settings (preserve user entries)
    _tmp=$(mktemp)
    if [ -s "$_settings_file" ] && jq '.' "$_settings_file" >/dev/null 2>&1; then
        # Preserve existing non-harness hooks
        _existing_hooks=$(jq '.hooks // {}' "$_settings_file")
        _merged=$(jq -s '.[0] * .[1]' "$_settings_file" - <<< "$_hooks_json")
        printf '%s' "$_merged" | jq '.' > "$_tmp" && mv "$_tmp" "$_settings_file"
    else
        printf '%s' "$_hooks_json" | jq '.' > "$_settings_file"
    fi

    log_verbose "Hooks config updated"
}

# ── Write .harnessignore ─────────────────────────────────────────────────────

write_harnessignore() {
    _ignore_file="$PROJECT_ROOT/.harnessignore"

    if [ -f "$_ignore_file" ]; then
        log_verbose ".harnessignore exists, skipping"
        return 0
    fi

    if [ "$FLAG_DRY_RUN" = true ]; then
        log_step "[dry-run] Would create .harnessignore"
        return 0
    fi

    cat > "$_ignore_file" <<'IGNEOF'
# Harness ignore — directories skipped during discovery
# Same format as .gitignore

node_modules/
.git/
.next/
.nuxt/
dist/
build/
__pycache__/
.venv/
venv/
vendor/
target/
.terraform/
.vercel/
coverage/
.cache/
tmp/
IGNEOF

    log_verbose "Created .harnessignore"
}

# ── Main ─────────────────────────────────────────────────────────────────────

run_write() {
    log_info "Writing harness files..."

    if [ ! -f "$CONFIG_FILE" ]; then
        log_error "No config.json found. Run generate first."
        exit $EXIT_STATE_CONFLICT
    fi

    # Backup before write
    if [ "$FLAG_DRY_RUN" != true ]; then
        backup_current
    fi

    write_claude_md
    write_scoped_configs
    write_hooks_config
    write_harnessignore

    if [ "$FLAG_DRY_RUN" = true ]; then
        log_info "Dry run complete. No files were written."
    else
        log_success "Harness files written successfully."
    fi
}
